### ISSUE TITLE
Nuxt Error: Cannot find module 'extract-text-webpack-plugi] {n'

### ISSUE THREAD

**Issue by xxyyzz2050** [medfreeman/nuxt-netlify-cms-module#104]
```
 FATAL  [                                                            08:45:05
  [node_modules\nuxt-netlify-cms\dist\webpack.config.js:1
  Error: Cannot find module 'extract-text-webpack-plugi] {n'
      at Object.<anonymous> (node_modules\nuxt-netlify-cms\dist\webpack.config.js:22:33)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    code: 'MODULE_NOT_FOUND'
  }
]
```

   ╭─────────────────────────────────────────────────────────────╮
   │                                                             │
   │   ✖ Nuxt Fatal Error                                        │
   │                                                             │
   │   Error: Cannot find module 'extract-text-webpack-plugin'   │
   │                                                             │
   ╰─────────────────────────────────────────────────────────────╯

I already installed webpack as devDependency but couldn't resolve the issue
adding extract-text-webpack-plugin resolved the issue, but I have to install all webpack plugins that used in this package

**Comment by medfreeman** [comment]
closed in [v4.0.0](https://github.com/medfreeman/nuxt-netlify-cms-module/releases/tag/v4.0.0) release.
