### ISSUE TITLE
Unable to deploy project to Netlify

### ISSUE THREAD

**Issue by davidemorotti** [medfreeman/nuxt-netlify-cms-module#119]
Hi,

I installed **nuxt-netlify-cms** checking the branch **rclement-support-nuxt-2.0** out in order to support my Nuxt.js version (2.0.0).

Here the list of my node dependencies:
```
"dependencies": {
    "@nuxtjs/axios": "^5.0.0",
    "core-js": "^2.6.5",
    "cross-env": "^5.2.0",
    "express": "^4.16.3",
    "jquery": "^3.3.1",
    "nuxt": "^2.0.0",
    "owl.carousel": "^2.3.4"
  },
  "devDependencies": {
    "netlify-cms": "^2.4.2",
    "node-sass": "^4.10.0",
    "nodemon": "^1.11.0",
    "nuxt-netlify-cms": "medfreeman/nuxt-netlify-cms-module#rclement-support-nuxt-2.0",
    "sass-loader": "^7.1.0"
  }
```

It works well locally, but when I try to deploy the project on Netlify, I always get this error:
<img width="1137" alt="screenshot 2019-02-19 at 08 15 53" src="https://user-images.githubusercontent.com/1756593/52996678-a09fc800-341e-11e9-837b-c70d0e5beace.png">

What could I do in order to solve this?

Cheers,
Davide

**Comment by davidemorotti** [comment]
I updated now the **nuxt-netlify-cms** dependency:
`"nuxt-netlify-cms": "git+https://github.com/medfreeman/nuxt-netlify-cms-module.git#rclement-support-nuxt-2.0",`

Now it seems to find the module, this time I get a different error:
<img width="1203" alt="screenshot 2019-02-19 at 08 40 09" src="https://user-images.githubusercontent.com/1756593/52997866-ff1a7580-3421-11e9-917f-cbaa5c0c5d0b.png">

**Comment by medfreeman** [comment]
I just cut the [v4.0.0](https://github.com/medfreeman/nuxt-netlify-cms-module/releases/tag/v4.0.0) release.
Please tell me if the error is properly resolved.

**Comment by davidemorotti** [comment]
@medfreeman it works now, I just had to add the package `"@nuxt/common": "latest"` to the `devDependencies` object.

Thank you very much :)
