### ISSUE TITLE
Thorough integration documentation

### ISSUE THREAD

**Issue by template01** [medfreeman/nuxt-netlify-cms-module#17]
Hello, 

Really nice prospect of being able to integrate Netlify CMS in Nuxt. When running nuxt/vue-based apps i often come up short with nice solutions for content management. Especially for smaller projects involving users and clients not wanting/able to work without a G(UI). 

I've been struggling a bit with getting things going using this module. Usually when I start a Nuxt-project I use the default nuxt/starter template. Could you provide a working example for integrating the nuxt-netlify-cms-module in this standard template, also including nuxtent. 

All the best,
Lasse

**Comment by medfreeman** [comment]
Hi, thanks for your interest !
I'm in the process of making a starter template with nuxt + nuxtent + netlify-cms that i plan to also blog about.
I'll keep you updated, as other projects are also fighting for my time.

Best

**Comment by template01** [comment]
Sure thing :) Take your time. I'll be following. Cheers
