### ISSUE TITLE
Upgrade to Nuxt 1.0

### ISSUE THREAD

**Issue by liborvanek** [medfreeman/nuxt-netlify-cms-module#38]
Hi,
any plans for upgrade to Nuxt 1.0?

`We have a new internal hook system now, some modules can be broken with 1.0 if they were relying on this.nuxt.plugin(), instead, they will have to use this.hook()`
Unfortunatelly docs are not updated yet.

**Comment by dunepebbler** [comment]
Can confirm this plugin isn’t working with nuxt 1.00 currently.
I’ve been poking around and this.nuxt.plugin() should be replaced with this.nuxt.hook()

https://github.com/nuxt/nuxt.js/commit/f0ea07ea4be9d589b1269646830c9ebb5a5795c8

**Comment by medfreeman** [comment]
Hi, i'm looking into this right now.

**Comment by joshmanders** [comment]
Any progress on this?

**Comment by medfreeman** [comment]
No, got caught up in server migration tasks and regular work, and leaving for holidays...
I'll do it on sat April 14.
In the meantime, if someone wants to take a stab at it, should be pretty simple.
Check this to get an idea of how this is done: https://github.com/nuxt-community/modules/commit/8e2d69c385027c06b5fad20c79fb34b78eb0dd5e

**Comment by ekoeryanto** [comment]
maybe it's a best time to make the project as a part of @nuxt-community

**Comment by slathrop** [comment]
Beyond just making it easier to integrate Nuxt and Vue.js with Netlify CMS, I'd love to see a **rewrite/adaptation** of Netlify CMS in **Vue.js**!

...and **"Vuelify CMS"** was born 👶 😀 

and heck, with the naming being so close, why not use **Vuetify** for the UI?

**Comment by ekoeryanto** [comment]
@slathrop let's start it!

**Comment by medfreeman** [comment]
Resolved in latest version: https://github.com/medfreeman/nuxt-netlify-cms-module/releases ;
