### ISSUE TITLE
"dependency" is not a valid chunk sort mode

### ISSUE THREAD

**Issue by julienchazal** [medfreeman/nuxt-netlify-cms-module#56]
Hello, using nuxtjs 1.4.0 and running `nuxt` command i got : 
`dependency" is not a valid chunk sort mode` in my terminal and also here : `http://localhost:3000/admin`

Any ideas please ?
thx

**Comment by julienchazal** [comment]
up @medfreeman ?

**Comment by medfreeman** [comment]
I'll take a look this weekend !
----- Mail d'origine -----
De: Julien CHAZAL <notifications@github.com>
À: medfreeman/nuxt-netlify-cms-module <nuxt-netlify-cms-module@noreply.github.com>
Cc: Mehdi Lahlou <mehdi.lahlou@free.fr>, Mention <mention@noreply.github.com>
Envoyé: Tue, 19 Jun 2018 22:01:28 +0200 (CEST)
Objet: Re: [medfreeman/nuxt-netlify-cms-module] "dependency" is not a valid chunk sort mode (#56)

up @medfreeman ?

**Comment by medfreeman** [comment]
Hi,
did you try to update your `nuxt` version ?

**Comment by medfreeman** [comment]
It's probably caused by an old `html-webpack-plugin` dependency required by `nuxt`.
