### ISSUE TITLE
Compatibility with nuxt2 (`nuxt-edge`)

### ISSUE THREAD

**Issue by r0skar** [medfreeman/nuxt-netlify-cms-module#60]
Hi, I was wondering if support for Nuxt 2 or `nuxt-edge` is planned? I couldn't get the module to work with `nuxt-edge` and I figured its because its not yet supported(?)

**Comment by kamontat** [comment]
Here is some [Migration Guide](https://nuxtjs.org/guide/release-notes#the-long-but-peaceful-approach)

**Comment by kamontat** [comment]
Refer to #90: 

They said [extract-text-webpack-plugin](https://github.com/webpack-contrib/extract-text-webpack-plugin) 'Since webpack v4 the extract-text-webpack-plugin should not be used for css. Use [mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin) instead.'

**Comment by dev7ch** [comment]
getting error `TypeError: Cannot read property 'r' of undefined` on fresh `nuxt-edge` installation

**Comment by VonStruddle** [comment]
> getting error `TypeError: Cannot read property 'r' of undefined` on fresh `nuxt-edge` installation

Got the same after installing missing dependencies.

**Comment by medfreeman** [comment]
closed in [v4.0.0](https://github.com/medfreeman/nuxt-netlify-cms-module/releases/tag/v4.0.0) release.
