### ISSUE TITLE
Error: Cannot find module 'extract-text-webpack-plugin'

### ISSUE THREAD

**Issue by danchristian** [medfreeman/nuxt-netlify-cms-module#90]
Installing `nuxt-netlify-cms-module` following the instructions for the first time and get the following error when I `npm run build`

```
✖ fatal .../node_modules/nuxt-netlify-cms/dist/webpack.config.js:1
  Error: Cannot find module 'extract-text-webpack-plugin'
  at Object.<anonymous> (.../node_modules/nuxt-netlify-cms/dist/webpack.config.js:22:33)
  at Object.Module._extensions..js (module.js:663:10)
  at Object.Module._extensions..js (module.js:663:10)
```

**Comment by medfreeman** [comment]
Hi, please indicate your nuxt version so i can investigate.
Thanks !

**Comment by gridsystem** [comment]
I have this issue on nuxt 2.2.0

**Comment by medfreeman** [comment]
That's because it's not nuxt 2 compatible as of now.
I plan on doing this during the next few weeks.
cf. #60
